include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - lib/**.g.dart

linter:
  rules:
    library_private_types_in_public_api: false
    public_member_api_docs: false

formatter:
  trailing_commas: preserve
