name: flutter_ui_examples
description: Flutter UI Examples

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  gradient_text: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: CustomIcon
      fonts:
        - asset: assets/fonts/CustomIcon.ttf

    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu.ttf

    - family: VarelaRound
      fonts:
        - asset: assets/fonts/VarelaRound.ttf

    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf

    - family: Muli
      fonts:
        - asset: assets/fonts/Muli.ttf

    - family: MuliLight
      fonts:
        - asset: assets/fonts/MuliLight.ttf

    - family: MontserratBlack
      fonts:
        - asset: assets/fonts/MontserratBlack.ttf

    - family: MontserratMedium
      fonts:
        - asset: assets/fonts/MontserratMedium.ttf

    - family: CustomIconsFurniture
      fonts:
        - asset: assets/fonts/CustomIconsFurniture.ttf

    - family: SocialIcons
      fonts:
        - asset: assets/fonts/SocialIcons.ttf
