name: flutter_ui_examples
description: Flutter UI Examples

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  google_fonts: ^4.0.3
  simple_gradient_text: ^1.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^4.0.0+1

flutter:
  uses-material-design: true
  assets:
    - assets/images/adidas/
    - assets/images/furniture/
    - assets/images/login/
    - assets/images/music/
    - assets/images/onboarding/
    - assets/images/shopping/
    - assets/images/story/
    - assets/images/streaming/
    - assets/images/
  fonts:
    - family: CustomIcon
      fonts:
        - asset: assets/fonts/CustomIcon.ttf
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
    - family: CustomIconsFurniture
      fonts:
        - asset: assets/fonts/CustomIconsFurniture.ttf
    - family: SocialIcons
      fonts:
        - asset: assets/fonts/SocialIcons.ttf
