name: flutter_ui_examples
description: Flutter UI Examples

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: 3.19.0

dependencies:
  circular_seek_bar: ^1.1.1
  collection: ^1.18.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  simple_gradient_text: ^1.3.0
  uuid: ^4.4.0

dev_dependencies:
  build_runner: ^2.4.11
  flutter_gen_runner: ^5.5.0+1
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter_gen:
  output: lib/common/gen/
  line_length: 80

  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  generate: true
  assets:
    # - assets/images/adidas/
    # - assets/images/beer/
    # - assets/images/furniture/
    - assets/images/login/
    # - assets/images/music/
    - assets/images/onboarding/
    - assets/images/shopping/
    # - assets/images/story/
    # - assets/images/sneaky/
    # - assets/images/streaming/
    # - assets/images/
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
    - family: CustomIconsFurniture
      fonts:
        - asset: assets/fonts/CustomIconsFurniture.ttf
    - family: AvenirLTStd
      fonts:
        - asset: assets/fonts/AvenirLTStd/AvenirLTStd-Book.otf
          weight: 300
        - asset: assets/fonts/AvenirLTStd/AvenirLTStd-Roman.otf
        - asset: assets/fonts/AvenirLTStd/AvenirLTStd-Black.otf
          weight: 700
    - family: PoetsenOne
      fonts:
        - asset: assets/fonts/PoetsenOne/PoetsenOne-Regular.ttf
