name: flutter_ui_examples
description: Flutter UI Examples

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.7.0

dependencies:
  circular_seek_bar: ^1.1.0+2
  collection: ^1.17.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.6
  flutter_rating_bar: ^4.0.1
  google_fonts: ^4.0.3
  simple_gradient_text: ^1.2.4
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^4.0.0+1

flutter:
  uses-material-design: true
  assets:
    - assets/images/adidas/
    - assets/images/beer/
    - assets/images/furniture/
    - assets/images/login/
    - assets/images/music/
    - assets/images/onboarding/
    - assets/images/shopping/
    - assets/images/story/
    - assets/images/sneaky/
    - assets/images/streaming/
    - assets/images/
  fonts:
    - family: CustomIcon
      fonts:
        - asset: assets/fonts/CustomIcon.ttf
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
    - family: CustomIconsFurniture
      fonts:
        - asset: assets/fonts/CustomIconsFurniture.ttf
    - family: SocialIcons
      fonts:
        - asset: assets/fonts/SocialIcons.ttf
    - family: AvenirLTStd
      fonts:
        - asset: assets/fonts/AvenirLTStd/AvenirLTStd-Book.otf
          weight: 300
        - asset: assets/fonts/AvenirLTStd/AvenirLTStd-Roman.otf
        - asset: assets/fonts/AvenirLTStd/AvenirLTStd-Black.otf
          weight: 700
    - family: PoetsenOne
      fonts:
        - asset: assets/fonts/PoetsenOne/PoetsenOne-Regular.ttf
