name: flutter_ui_examples
description: Flutter UI Examples

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: 3.32.0

dependencies:
  circular_seek_bar: ^1.1.1
  collection: ^1.19.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  flutter_rating_bar: ^4.0.1
  gap: ^3.0.1
  google_fonts: ^6.2.1
  simple_gradient_text: ^1.3.0
  uuid: ^4.5.1
  vector_graphics: ^1.1.19

dev_dependencies:
  build_runner: ^2.5.3
  flutter_gen_runner: ^5.10.0
  flutter_test:
    sdk: flutter
  vector_graphics_compiler: ^1.1.17
  very_good_analysis: ^9.0.0

flutter_gen:
  output: lib/common/gen/
  line_length: 80

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/adidas/
    - assets/images/beer/
    - assets/images/furniture/
    - path: assets/svg/furniture/
      transformers:
        - package: vector_graphics_compiler
    - assets/images/ice_cream/
    - path: assets/svg/ice_cream/
      transformers:
        - package: vector_graphics_compiler
    - assets/images/login/
    - path: assets/svg/login/
      transformers:
        - package: vector_graphics_compiler
    - assets/images/music/
    - assets/images/onboarding/
    - assets/images/shopping/
    - path: assets/svg/shopping/
      transformers:
        - package: vector_graphics_compiler
    - assets/images/sneaky/
    - assets/images/story/
    - path: assets/svg/story/
      transformers:
        - package: vector_graphics_compiler
    - assets/images/streaming/
  fonts:
    - family: AvenirLTStd
      fonts:
        - asset: assets/fonts/AvenirLTStd/AvenirLTStd-Book.otf
          weight: 300
        - asset: assets/fonts/AvenirLTStd/AvenirLTStd-Roman.otf
        - asset: assets/fonts/AvenirLTStd/AvenirLTStd-Black.otf
          weight: 700
    - family: PoetsenOne
      fonts:
        - asset: assets/fonts/PoetsenOne/PoetsenOne-Regular.ttf
    - family: Ritts
      fonts:
        - asset: assets/fonts/Ritts/Ritts-Cursive.ttf
    - family: MuseoSansCyrl
      fonts:
        - asset: assets/fonts/MuseoSansCyrl/Museo-Sans-Cyrl-300.ttf
          weight: 300
        - asset: assets/fonts/MuseoSansCyrl/Museo-Sans-Cyrl-700.ttf
          weight: 700
